#!/bin/sh

blockdev_enabled() {
    return 0
}

blockdev_run() {
    # Trigger ioctl to read partitions
    /sbin/blockdev --rereadpt /dev/mmcblk0

    # Starting with 32.7.1 BSP update, it's necessary to
    # wait a few seconds for the partitions as well as their symlinks to
    # be populated, otherwise the fsck and resindataexpander
    # modules will not run. Five seconds proved to be enough in our tests.
    sleep 5
}
