#!/bin/sh

FREESPACE_LIMIT=10
datapart=$(readlink -f /dev/disk/by-partlabel/resin-data)
datadev=$(lsblk $datapart -n -o PKNAME)

resindataexpander_enabled() {
    # On flasher avoid expanding partition
    if [ "$bootparam_flasher" = "true" ]; then
        echo "[INFO] Flasher detected. Avoiding expand partition mechanism."
        return 1
    fi

    # If the secondary GPT is not the end of the disk, parted will wait
    # and act on 'fix' argument to silently fix it. If GPT is already fixed,
    # nothing else happens.
    parted /dev/$datadev print fix 2>&1 > /dev/null ; partprobe ; sync

    for freespace in $(parted -m /dev/$datadev unit MiB print free | grep free | cut -d: -f4 | sed 's/MiB//g'); do
        if [ $(echo $freespace \> $FREESPACE_LIMIT | bc -l) == "1" ]; then
            return 0
        fi
    done
    return 1
}

resindataexpander_run() {
    # On jetsons, the data partition has a different index
    # which appears to differ from one l4t to another

    resin_data_index=$(parted -s /dev/$datadev unit S print | grep "resin-data" | tr '\n' ' '  | awk '{print $1}')

    info "resindataexpander: Expand data partition... "
    parted -s /dev/$datadev -- resizepart $resin_data_index 100%
    info "resindataexpander: Finished expanding data partition."

    partprobe
    sync
}
