TTYS_jetson-nano=" ttyS0 tty1"
TTYS_jetson-nano-emmc =" ttyS0 tty1"
TTYS_jetson-nano-2gb-devkit =" ttyS0 tty1"
TTYS_jetson-xavier=" ttyTHS0 tty1"
TTYS_jetson-xavier-nx-devkit-emmc=" ttyTHS0 tty1"
TTYS_jetson-xavier-nx-devkit=" ttyTHS0 tty1"
TTYS_tegra186=" ttyS0 tty1"
TTYS_jetson-tx1=" ttyS0 tty1"
