#!/bin/sh

set -o errexit

flash() {
    for line in $(cat $1); do
        part_name=$(echo $line | cut -d ':' -f 1)
        file_name=$(echo $line | cut -d ':' -f 2)

        dd oflag=dsync if="/opt/tegra-binaries/$file_name" of="/dev/disk/by-partlabel/$part_name"
    done
}

flash "/opt/tegra-binaries/partition_specification186.txt"

# we create boot0.img inside tegra186-flash-dry
echo 0 > /sys/block/mmcblk0boot0/force_ro
dd if=/opt/tegra-binaries/boot0.img of=/dev/mmcblk0boot0 ; sync
echo 1 > /sys/block/mmcblk0boot0/force_ro

