#!/bin/sh
set -o errexit

# Script which writes the appropriate
# device tree with embedded cmdline
# and updates the kernel, as well as
# the rest of the bootloader binaries

. /usr/libexec/os-helpers-fs

bootloader_device="/dev/mtdblock0"
bootloader_blob="/opt/tegra-binaries/boot0.img"
partspec="/opt/tegra-binaries/partition_specification194_nxde.txt"
new_part=$(findmnt --noheadings --canonicalize --output SOURCE "/mnt/sysroot/inactive" -t ext4)

info_log()
{
    echo "[INFO] $@"
}

info_log "New partition is ${new_part}"

rootstr=$(get_dev_label "${new_part}")
rootl=""

update_needed() {
    current_update_file=${1}
    device=${2}
    update_size=$(ls -al $current_update_file | awk '{print $5}')
    update_md5sum=$(md5sum $current_update_file | awk '{print $1'})
    existing_md5sum=$(dd if=$device bs=1 count=$update_size status=none | md5sum | awk '{print $1}')

    if [ ! "$existing_md5sum" = "$update_md5sum" ]; then
        echo 1
    else
        echo 0
    fi
}

case "$rootstr" in
    *resin-rootA*)
        rootl="A"
        ;;
    *resin-rootB*)
        rootl="B"
        ;;
    *)
        rootl="Undefined"
        ;;
esac

info_log "New root is resin-root${rootl}"

dtbname=$(cat "$partspec" | grep "kernel-dtb_b" | cut -d ':' -f 2 | awk -F'_sigheader' '{print $1}')
dtbfile="${dtbname}-root${rootl}_sigheader.dtb.encrypt"
kernel="boot_sigheader.img.encrypt"
partitions=$(cat ${partspec})

for n in ${partitions}; do
    part_name=$(echo $n | cut -d ':' -f 1)
    file_name=$(echo $n | cut -d ':' -f 2)

    if [ -z "${part_name##*kernel*}" ] || [ -z "${part_name##*bootloader-dtb*}" ] || [ $file_name = "none.bin" ]; then
        continue
    fi

    file_path=$(get_state_path_from_label $part_name)

    if [ "x$file_path" = "x" ]; then
        continue
    fi

    src="/opt/tegra-binaries/${file_name}"
    dst="$file_path"

    if [ $(update_needed $src $dst) -eq 1 ]; then
        info_log "Will update ${dst} ..."
        dd if=${src} of=${dst}
        dd if=${src} of="${dst}_b"
    else
        info_log "No need to update ${dst}"
    fi
done

# DTB contains root partition, update is mandatory
info_log "Writing ${dtbfile} to specific partitions..."
dd if=/opt/tegra-binaries/${dtbfile} of=$(get_state_path_from_label "kernel-dtb")
dd if=/opt/tegra-binaries/${dtbfile} of=$(get_state_path_from_label "kernel-dtb_b")

info_log "Writing kernel ${kernel} to specific partitions..."
dd if=/opt/tegra-binaries/${kernel}  of=$(get_state_path_from_label "kernel")
dd if=/opt/tegra-binaries/${kernel}  of=$(get_state_path_from_label "kernel_b")

existing_bootloader_md5sum=$(dd if=$bootloader_device bs=1M status=none | md5sum | awk '{print $1}')
update_bootloader_md5sum=$(md5sum $bootloader_blob | awk '{print $1}')

if [ ! "$existing_bootloader_md5sum" = "$update_bootloader_md5sum" ]; then
    info_log "Will update bootloader device"
    flash_erase /dev/mtd0 0 0
    dd if=$bootloader_blob of=$bootloader_device bs=1M
else
    info_log "No need to update bootloader device"
fi

sync

info_log "Done."
