#!/bin/sh
set -o errexit

# Script which writes the appropriate
# device tree with embedded cmdline
# and updates the kernel, as well as
# the rest of the bootloader binaries

. /usr/libexec/os-helpers-fs

partspec="/resin-boot/bootfiles/partition_specification194.txt"
new_part=$(findmnt --noheadings --canonicalize --output SOURCE "/mnt/sysroot/inactive" -t ext4)

info_log()
{
    echo "[INFO] $@"
}

info_log "New partition is ${new_part}"

get_label_suffix_by_slot()
{
    if [ $1 -eq 0 ]; then
        echo ''
    else
        echo '_b'
    fi
}

if ! command -v tegra-boot-control &> /dev/null
then
    info_log "Could not find tegra-boot-control!"
    exit 1
fi

redundancy_state=$(/usr/bin/tegra-boot-control -s | awk -F 'Redundancy:' '{print $2}' | awk '{print $1}' | tr -d '\n')
info_log "Redundancy is currently ${redundancy_state}"

# Enable boot slot redundancy
tegra-boot-control -e
curr_slot=$(/usr/bin/tegra-boot-control -c)
info_log "New active slot is $((new_slot = ! curr_slot))"
new_label_suffix=$(get_label_suffix_by_slot ${new_slot})

rootstr=$(get_dev_label "${new_part}")
rootl=""

update_needed() {
    current_update_file=${1}
    device=${2}
    update_size=$(ls -al $current_update_file | awk '{print $5}')
    update_md5sum=$(md5sum $current_update_file | awk '{print $1'})
    existing_md5sum=$(dd if=$device bs=1 count=$update_size status=none | md5sum | awk '{print $1}')

    if [ ! "$existing_md5sum" = "$update_md5sum" ]; then
        echo 1
    else
        echo 0
    fi
}

case "$rootstr" in
    *resin-rootA*)
        rootl="A"
        ;;
    *resin-rootB*)
        rootl="B"
        ;;
    *)
        rootl="Undefined"
        ;;
esac

info_log "New root is resin-root${rootl}"

dtbname=$(cat "$partspec" | grep "kernel-dtb_b" | cut -d ':' -f 2 | awk -F'_sigheader' '{print $1}')
dtbfile="${dtbname}-root${rootl}_sigheader.dtb.encrypt"
kernel="boot_sigheader.img.encrypt"

partitions=$(cat "${partspec}")
for n in ${partitions}; do
    part_name=$(echo $n | cut -d ':' -f 1)
    file_name=$(echo $n | cut -d ':' -f 2)

    if [ -z "${part_name##*kernel*}" ] || [ -z "${part_name##*bootloader-dtb*}" ] || [ $file_name = "none.bin" ]; then
        continue
    fi

    file_path=$(get_state_path_from_label $part_name)

    if [ "x$file_path" = "x" ]; then
        continue
    fi

    src="/resin-boot/bootfiles/$file_name"
    dst="$file_path"

    if [ $(update_needed $src $dst) -eq 1 ]; then
        info_log "Will update ${dst}${new_label_suffix} ..."
        dd if=${src} of="${dst}${new_label_suffix}"
    else
        info_log "No need to update ${dst}${new_label_suffix}"
    fi
done

# root is contained in the dtb cmdline, needs to be updated to switch rootfs, but only in the next active slot
info_log "Writing ${dtbfile} to specific partitions - suffix is ${new_label_suffix}."

dd if=/resin-boot/bootfiles/${dtbfile} of=$(get_state_path_from_label "bootloader-dtb${new_label_suffix}")
dd if=/resin-boot/bootfiles/${dtbfile} of=$(get_state_path_from_label "kernel-dtb${new_label_suffix}")

info_log "Writing kernel ${kernel} to specific partitions..."

dd if=/resin-boot/bootfiles/${kernel}  of=$(get_state_path_from_label "kernel${new_label_suffix}")

info_log "Updating boot image on hw partition mmcblk0boot0..."

echo 0 > /sys/block/mmcblk0boot0/force_ro
dd if=/resin-boot/bootfiles/boot0.img of=/dev/mmcblk0boot0
sync
echo 1 > /sys/block/mmcblk0boot0/force_ro

# Update slot selection after the boot memory was updated, otherwise
# scratch register contents will be lost.
info_log "Setting active slot to ${new_slot}"
/usr/bin/tegra-boot-control -e
/usr/bin/tegra-boot-control -a ${new_slot}

info_log "Done."
