#!/bin/sh
set -o errexit

# Script which writes the appropriate
# device tree with embedded cmdline
# and updates the kernel, as well as
# the rest of the bootloader binaries

. /usr/libexec/os-helpers-fs

bootloader_device="/dev/mtdblock0"
bootloader_blob="/opt/tegra-binaries/boot0.img"
partspec=$(find "/opt/tegra-binaries/" | grep "partition_specification194_nx")
new_part=$(findmnt --noheadings --canonicalize --output SOURCE "/mnt/sysroot/inactive" -t ext4)

info_log()
{
    echo "[INFO] $@"
}

info_log "New partition is ${new_part}"

get_label_suffix_by_slot()
{
    if [ $1 -eq 0 ]; then
        echo ''
    else
        echo '_b'
    fi
}

if ! command -v tegra-boot-control &> /dev/null
then
    info_log "Could not find tegra-boot-control!"
    exit 1
fi

redundancy_state=$(/usr/bin/tegra-boot-control -s | awk -F 'Redundancy:' '{print $2}' | awk '{print $1}' | tr -d '\n')
info_log "Redundancy is currently ${redundancy_state}"

# Enable boot slot redundancy
tegra-boot-control -e
curr_slot=$(/usr/bin/tegra-boot-control -c)
info_log "New active slot is $((new_slot = ! curr_slot))"
new_label_suffix=$(get_label_suffix_by_slot ${new_slot})

rootstr=$(get_dev_label "${new_part}")
rootl=""

update_needed() {
    current_update_file=${1}
    device=${2}
    update_size=$(ls -al $current_update_file | awk '{print $5}')
    update_md5sum=$(md5sum $current_update_file | awk '{print $1'})
    existing_md5sum=$(dd if=$device bs=1 count=$update_size status=none | md5sum | awk '{print $1}')

    if [ ! "$existing_md5sum" = "$update_md5sum" ]; then
        echo 1
    else
        echo 0
    fi
}

case "$rootstr" in
    *resin-rootA*)
        rootl="A"
        ;;
    *resin-rootB*)
        rootl="B"
        ;;
    *)
        rootl="Undefined"
        ;;
esac

info_log "New root is resin-root${rootl}"

dtbname=$(cat "$partspec" | grep "kernel-dtb_b" | cut -d ':' -f 2 | awk -F'_sigheader' '{print $1}')
dtbfile="${dtbname}-root${rootl}_sigheader.dtb.encrypt"
kernel="boot_sigheader.img.encrypt"
partitions=$(cat ${partspec})

for n in ${partitions}; do
    part_name=$(echo $n | cut -d ':' -f 1)
    file_name=$(echo $n | cut -d ':' -f 2)

    if [ -z "${part_name##*kernel*}" ] || [ -z "${part_name##*bootloader-dtb*}" ] || [ $file_name = "none.bin" ]; then
        continue
    fi

    file_path=$(get_state_path_from_label $part_name)

    if [ "x$file_path" = "x" ]; then
        continue
    fi

    src="/opt/tegra-binaries/${file_name}"
    dst="$file_path"

    if [ $(update_needed $src $dst) -eq 1 ]; then
        info_log "Will update ${dst}${new_label_suffix} ..."
        dd if=${src} of="${dst}${new_label_suffix}"
    else
        info_log "No need to update ${dst}${new_label_suffix}"
    fi
done

# DTB contains root partition, update is mandatory on the new boot slot, before switching it to active
info_log "Writing ${dtbfile} to specific partitions..."
dd if=/opt/tegra-binaries/${dtbfile} of=$(get_state_path_from_label "kernel-dtb${new_label_suffix}")

info_log "Writing kernel ${kernel} to specific partitions..."
dd if=/opt/tegra-binaries/${kernel} of=$(get_state_path_from_label "kernel${new_label_suffix}")

existing_bootloader_md5sum=$(dd if=$bootloader_device bs=1M status=none | md5sum | awk '{print $1}')
update_bootloader_md5sum=$(md5sum $bootloader_blob | awk '{print $1}')

if [ ! "$existing_bootloader_md5sum" = "$update_bootloader_md5sum" ]; then
    info_log "Will update bootloader device"
    flash_erase /dev/mtd0 0 0 || true
    dd if=$bootloader_blob of=$bootloader_device bs=1M
else
    info_log "No need to update bootloader device"
fi

# Sync internal memory
sync /dev/mmcblk0

# Update slot selection after the qspi was updated, otherwise
# scratch register contents will be lost
info_log "Setting active slot to ${new_slot}"
/usr/bin/tegra-boot-control -e
/usr/bin/tegra-boot-control -a ${new_slot}

info_log "Done."
