TTYS:jetson-nano=" ttyS0 tty1"
TTYS:jetson-nano-emmc =" ttyS0 tty1"
TTYS:jetson-nano-2gb-devkit =" ttyS0 tty1"
TTYS:jetson-xavier=" ttyTHS0 tty1"
TTYS:jetson-xavier-nx-devkit-emmc=" ttyTHS0 tty1"
TTYS:jetson-xavier-nx-devkit=" ttyTHS0 tty1"
TTYS:jetson-tx2=" ttyS0 tty1"
TTYS:jetson-tx1=" ttyS0 tty1"
