name: 'Deploy on release tag'

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+\+?r?e?v?*
      - v20[0-9][0-9].[0-1]?[1470].[0-9]+

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  release-on-tag:
    uses: balena-os/github-workflows/.github/workflows/build_and_deploy.yml@4b1cfb9e7c0909a6d9547f381d5ac43cf0a82190 # v0.0.28
    with:
      deployTo: "production"
    secrets: inherit
